
export const a_FETCH_PACKAGING_KIND_LIST = 'FETCH_PACKAGING_KIND_LIST'
export const a_FETCH_PACKAGING_STATE_LIST = 'FETCH_PACKAGING_STATE_LIST'

export const m_SET_PACKAGING_KIND_LIST = 'SET_PACKAGING_KIND_LIST'
export const m_SET_PACKAGING_STATE_LIST = 'SET_PACKAGING_STATE_LIST'