
export const m_SET_FOOD_CATEGORY_LIST = 'SET_FOOD_CATEGORY_LIST'

export const a_FETCH_FOOD_CATEGORY_LIST = 'FETCH_FOOD_CATEGORY_LIST'
export const a_POST_FOOD_CATEGORY = 'POST_FOOD_CATEGORY'
export const a_UPDATE_FOOD_CATEGORY = 'UPDATE_FOOD_CATEGORY'
export const a_DELETE_FOOD_CATEGORY = 'DELETE_FOOD_CATEGORY'
