

export const m_SET_STOCKS = 'SET_STOCK_LIST'
export const m_UPDATE_STOCK_LIST = 'UPDATE_STOCK_LIST'
export const m_SET_SELECTED_STOCK_ID = 'SET_SELECTED_STOCK_ID'

export const a_FETCH_STOCKS = 'FETCH_STOCKS'
export const a_POST_STOCK = 'POST_STOCK'
export const a_POST_STOCK_ITEM = 'POST_STOCK_ITEM'
export const a_DELETE_STOCK = 'DELETE_STOCK'

export const g_SELECTED_STOCK = 'SELECTED_STOCK'
export const g_FOOD_KINDS_IN_SELECTED_STOCK = 'FOOD_KINDS_IN_SELECTED_STOCK'