export const m_SET_SELECTED_STOCK_ITEM_FOOD_KIND_ID = 'SET_SELECTED_STOCK_ITEM_FOOD_KIND_ID'

export const a_POST_STOCK_ITEM_STATE = 'POST_STOCK_ITEM_STATE'

export const g_SELECTED_STOCK_ITEM = 'SELECTED_STOCK_ITEM'
export const g_STATUS_OF_POST_STOCK_ITEM_STATE = 'STATUS_OF_POST_STOCK_ITEM_STATE'