export const a_LOGIN = 'LOGIN'
export const a_LOGOUT = 'LOGOUT'
export const a_REGISTER = 'REGISTER'
export const a_REFRESH_ACCESS_TOKEN = 'REFRESH_ACCESS_TOKEN'

export const g_LOGIN_REQ_DATA = 'LOGIN_REQ_DATA'
export const g_LOGIN_REQ_STATUS = 'LOGIN_REQ_STATUS'

export const g_REGISTER_REQ_DATA = 'REGISTER_REQ_DATA'
export const g_REGISTER_REQ_STATUS = 'REGISTER_REQ_STATUS'