export const m_SET_SESSION = 'SET_SESSION'
export const m_SET_SESSION_LOGGED_OUT = 'SET_SESSION_LOGGED_OUT'

export const a_LOGIN = 'LOGIN'
export const a_LOGOUT = 'LOGOUT'
export const a_REGISTER = 'REGISTER'
export const a_REFRESH_ACCESS_TOKEN = 'REFRESH_ACCESS_TOKEN'

export const g_GET_IS_LOGGED_IN = 'GET_IS_LOGGED_IN'
export const g_USER_CLAIMS = 'USER_CLAIMS'

export const g_LOGIN_REQ_DATA = 'LOGIN_REQ_DATA'
export const g_LOGIN_REQ_STATUS = 'LOGIN_REQ_STATUS'

export const g_REGISTER_REQ_DATA = 'REGISTER_REQ_DATA'
export const g_REGISTER_REQ_STATUS = 'REGISTER_REQ_STATUS'

export const g_LOGOUT_ACCESS_REQ_STATUS = 'LOGOUT_ACCESS_REQ_STATUS'
export const g_LOGOUT_REFRESH_REQ_STATUS = 'LOGOUT_REFRESH_REQ_STATUS'