export const a_SEND_RESET_LINK = 'SEND_RESET_LINK'
export const a_RESET_PASSWORD = 'RESET_PASSWORD'


export const g_SEND_RESET_LINK_REQ_STATUS = 'SEND_RESET_LINK_REQ_STATUS'
export const g_SEND_RESET_LINK_REQ_DATA = 'SEND_RESET_LINK_REQ_DATA'

export const g_RESET_PASSWORD_REQ_STATUS = 'RESET_PASSWORD_REQ_STATUS'
export const g_RESET_PASSWORD_REQ_DATA = 'RESET_PASSWORD_REQ_DATA'