
export const m_SET_FOOD_KIND_LIST = 'SET_FOOD_KIND_LIST'
export const m_SET_SELECTED_FOOD_KIND_ID = 'SET_SELECTED_FOOD_KIND_ID'

export const a_FETCH_FOOD_KIND_LIST = 'FETCH_FOOD_KIND_LIST'
export const a_POST_FOOD_KIND = 'POST_FOOD_KIND'
export const a_UPDATE_FOOD_KIND = 'UPDATE_FOOD_KIND'
export const a_DELETE_FOOD_KIND = 'DELETE_FOOD_KIND'

export const g_SELECTED_FOOD_KIND = 'SELECTED_FOOD_KIND'
export const g_GET_FOOD_KIND_BY_ID = 'GET_FOOD_KIND_BY_ID'
export const g_GET_SELECTED_FOOD_KIND_UOM = 'GET_SELECTED_FOOD_KIND_UOM'
export const g_STATUS_OF_POST_FOOD_KIND = 'STATUS_OF_POST_FOOD_KIND'
export const g_DATA_FROM_DELETE_FOOD_KIND = 'DATA_FROM_DELETE_FOOD_KIND'